services:
  - type: web
    name: jobtrackr-api
    runtime: node
    rootDir: server
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
